top_title = "Yin | | | |"
title = "ଯାନ୍ତ୍ରିକ ଦକ୍ଷତା ଏବଂ ଉପକରଣଗୁଡ଼ିକ |"
subtitle = "ମୋର ଅନୁସନ୍ଧାନରେ ବ୍ୟବହୃତ ତତ୍ତ୍ୱଗତ framework ାଞ୍ଚା, ଗଣନାକାରୀ ଉପକରଣ ଏବଂ ପ୍ରୋଗ୍ରାମିଂ ଭାଷା |"
image = "images/about/me.jpg"
[[skills]]
title = "ଗିରିଜ୍"
percent = "95"

[[skills]]
title = "ପାଇଥନ୍ / NumPy / SciPy (ବିଶେଷଜ୍ଞ)"
percent = "92"

[[skills]]
title = "ହାଲୁକା-ଫ୍ରଣ୍ଟ୍ କ୍ୱାର୍କ ମଡେଲ୍ (LFQM)"
percent = "95"

[[skills]]
title = "NJL / DS-BSE / ଆସା ଆସା ଆସା ଆସା ଆସା ଆସା ଆସା ଆଜ ଆଜ ଆସା ଆଜ ଆଜ ଆଜ | | | |"
percent = "85"

[[skills]]
title = "LHAPDF / xFitter / DGLAP / CSS | | | |"
percent = "90"

[[skills]]
title = "ଲାଟେକ୍ସ୍ | | |"
percent = "95"

[[skills]]
title = "ଗିରି ଚାରାକ / ML / କିଜ ଆଜଜ ଆଜଜ (ଆଜଜ ଆଜିକା)"
percent = "75"

[[skills]]
title = "C ++ / Linux / Git"
percent = "60"

