title = "ଗିରିଜ୍"
description = "|\n\nଏନଆଇଟି ଜଲନ୍ଧର କିର କିଜ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ڭ ەر ର୍ଚ୍ଚ ର୍ଚ୍ଚ ڭ ର୍ଚ୍ଚ ର୍ଚ୍ଚ ର୍ଚ୍ଚ"
button_name = "Contact Me"
button_url = "contact"
image = "images/hero/me1.jpg"

[[gallery]]
image = "images/gallery/defense-presenting-qcd.jpg"
caption = "ପିଏଚଡି ଫାଇନାଲ ଡିଫେନ୍ସ, NIT ଜାଲନ୍ଧର"

[[gallery]]
image = "images/gallery/defense-group-photo.jpg"
caption = "ଡିଫେନ୍ସ ପରେ ଗ୍ରୁପ ଫଟୋ, NIT ଜାଲନ୍ଧର"

[[gallery]]
image = "images/gallery/defense-friends-nitj.jpg"
caption = "ML group photo at post-Viva (The BoYz)"

[[gallery]]
image = "images/gallery/defense-thesis-examiner.jpg"
caption = "Smiling at the place, where I lost my smile on 22nd Dec, 2025"

[[gallery]]
image = "images/gallery/academia-sinica-taiwan.jpg"
caption = "Academia Sinica, Taiwan"

[[gallery]]
image = "images/gallery/colleague-selfie.jpg"
caption = "Dr. Narinder Kumar ସହ LAB-119, NIT-J DOP ରେ"

[[gallery]]
image = "images/gallery/friends-metro-selfie.jpg"
caption = "Vidit ସହ ଦିଲ୍ଲୀ ମେଟ୍ରୋରେ"

[[gallery]]
image = "images/gallery/switzerland-alps.jpg"
caption = "Zuoz, Swiss Alps"

[[gallery]]
image = "images/gallery/moscow-bolshoi.jpg"
caption = "Bolshoi Theatre, Moscow"

[[gallery]]
image = "images/gallery/red-square-moscow.jpg"
caption = "Red Square, Moscow"

[[gallery]]
image = "images/gallery/hanoi-airport.jpg"
caption = "Manali"

[[gallery]]
image = "images/gallery/jinr-office-dubna.jpg"
caption = "IIT Mandi"

[[gallery]]
image = "images/gallery/adiyogi-coimbatore.jpg"
caption = "Adiyogi, Coimbatore"

[[gallery]]
image = "images/gallery/hilltop-bengaluru.jpg"
caption = "Nandi Hills, Bengaluru"

[[gallery]]
image = "images/gallery/moonlit-rooftop.jpg"
caption = "BLTP, JINR Dubna"

[[gallery]]
image = "images/gallery/hilltop-sunset.jpg"
caption = "Hilltop Sunset, Dharamshala"

[[gallery]]
image = "images/gallery/office-research.jpg"
caption = "Research Lab, NIT Jalandhar"

